name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/know_hosts
          ssh-add - <<< "${{ secrets.SSH_KEY }}"
      - name: Deploy
        run: scp -r public/ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.DESTINATION_PATH }}
      # Runs a set of commands using the runners shell
